<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                Connect Management
                <input type="button" class="da-tooltip-sw da-button gray" id="da-ex-dialog-form" value="Add new" original-title="Click here to add new menu">
            </span>
            
        </div>
        <div class="da-panel-content">
            <table id="da-ex-datatable-numberpaging" class="da-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Title</th>
                        <th>Order</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        if(count($this->data)>0){
                            foreach ($this->data as $result){
                                echo "<tr>";
                                    echo "<td>".$result['id']."</td>";
                                    echo "<td>".$result['title']."</td>";
                                    echo "<td>".$result['order']."</td>";
                                    echo "<td class=\"da-icon-column\">";
                                        echo "<a href=\"#\" class=\"viewconnect\" id=\"".$result['id']."\"><img src=\"images/icons/color/magnifier.png\" /></a>";
                                        echo "<a href=\"#\" class=\"updateconnect\" id=\"".$result['id']."\"><img src=\"images/icons/color/pencil.png\" /></a>";
                                        echo "<a href=\"#\" class=\"deleteconnect\" id=\"".$result['id']."\"><img src=\"images/icons/color/cross.png\" /></a>";
                                    echo "</td>";
                                echo "</tr>";                                
                            }
                        }
                     ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    var id_update="";
    jQuery(document).ready(function() {
        jQuery("#da-ex-dialog-form-div,#dialog_view_connect,#dialog_update_connect").dialog({
            autoOpen:false,
            title:"Add Connect",
            modal:true,
            width:"640"
        }).find("#da-ex-dialog-dp").datepicker({dateFormat:"yy-mm-dd"}).end().find("form").validate({
            rules:{
                reqTitle:{required:true},
                reqIcon:{required:true,accept:["jpeg","jpg","png","gif"]},
                reqLink:{required:true},
                reqOrder:{required:true,digits:true},
                reqStatus:{required:true}},
            invalidHandler:function(f,d){
                var g=d.numberOfInvalids();
                if(g){var e=g==1?"You missed 1 field. It has been highlighted":"You missed "+g+" fields. They have been highlighted";
                    jQuery("#da-validate-error").html(e).show()
                }else{
                    jQuery("#da-validate-error").hide()
                }
            }
        });
        jQuery("#da-ex-dialog-form").bind("click",function(d){
            jQuery("#da-ex-dialog-form-div").dialog("option",{modal:true}).dialog("open");
            d.preventDefault();
        });
        jQuery(".viewconnect").click(function(evt){
            evt.preventDefault();
            var id=jQuery(this).attr("id");
            jQuery.ajax({
                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/getconnect",
                type:"POST",
                data:{data:id},
                success:function(result){
                    var obj = $.parseJSON(result);
                    jQuery("#view_title").val(obj[0]['title']);
                    jQuery("#view_image").attr('src',"<?php echo 'http://'.URL_CONFIG;?>"+obj[0]['icon']);
                    jQuery("#view_link").val(obj[0]['link']);
                    jQuery("#view_order").val(obj[0]['order']);
                    jQuery("#view_statuss").val(obj[0]['status']);
                    jQuery("#dialog_view_connect").dialog({
                        title:"View Connect",
                        modal:true,
                        width:"640",
                        beforeClose: function(event, ui) {
                            jQuery("#view_title").val("");
                            jQuery("#view_image").attr('src',"");
                            jQuery("#view_link").val("");
                            jQuery("#view_order").val("");
                            jQuery("#view_statuss").val("");
                        },
                        buttons: { "Ok": function() { $(this).dialog("close"); } }
                    }).dialog("open");
                }
            });
        });
        //Show form update connect
        jQuery(".updateconnect").click(function(evt){
            evt.preventDefault();
            var id=jQuery(this).attr("id");
            id_update=id;
            jQuery.ajax({
                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/getconnect",
                type:"POST",
                data:{data:id},
                success:function(result){
                    var obj = $.parseJSON(result);
                    jQuery("#up_title").val(obj[0]['title']);
                    jQuery("#up_image").attr('src',"<?php echo 'http://'.URL_CONFIG;?>"+obj[0]['icon']);
                    jQuery("#up_link").val(obj[0]['link']);
                    jQuery("#up_order").val(obj[0]['order']);
                    jQuery("#up_statuss").val(obj[0]['status']);
                    jQuery("#dialog_update_connect").dialog({
                        title:"Update Connect",
                        modal:true,
                        width:"640",
                        beforeClose: function(event, ui) {
                            jQuery("#up_title").val("");
                            jQuery("#up_image").attr('src',"");
                            jQuery("#up_link").val("");
                            jQuery("#up_order").val("");
                            jQuery("#up_statuss").val("");
                        }
                    }).dialog("open");
                }
            });
        });
        jQuery(".deleteconnect").click(function(){
            var choose= confirm("You are want to delete?");
            if(choose){
                var id = jQuery(this).attr("id");
                jQuery.ajax({
                    url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deleteconnect",
                    type:"POST",
                    data:{data:id},
                    success:function(result){
                        alert(result);
                        location.href="<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/connect";
                    }
                });
            }
            
        });
    });
    
    
</script>
<div id="da-ex-dialog-form-div" class="no-padding">
    <form id="da-ex-dialog-form-val" class="da-form">

        <div id="da-validate-error" class="da-message error" style="display:none;"></div>

        <div class="da-form-inline">

            <div class="da-form-row">

                <label>Title:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqTitle" id="title" />

                </div>

            </div>
            <div class="da-form-row">

                <label>Icon:</label>
                <div class="customfiles da-form-item large">
                    <input type="file" id="file-upload" class=" da-custom-file customfile-input" style="left: -14px; top: 15px; ">

                    <span id="status" ></span>

                    <ul id="files" ></ul>
                    <script type="text/javascript" >
                        var url_logo="";
                        $(function(){
                        var btnUpload=$('#file-upload');
                        var status=$('#status');
                        var folder="<?php echo ROOT_CONFIG.'/public/data/connect/'?>";
                        new AjaxUpload(btnUpload, {
                            action: '<?php echo "http://".URL_CONFIG."/public/admin/index/uploadiconconnect";?>',
                            name: 'uploadfile',
                            onSubmit: function(file, ext){
                                 if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){ 
                                    // extension is not allowed 
                                    status.text('Only JPG, PNG or GIF files are allowed');
                                    return false;
                                }
                                status.text('Uploading...');
                            },
                            onComplete: function(file, response){
                                //On completion clear the status
                                status.text('');
                                //Add uploaded file to list
                                if(response==="success"){
                                    var src='<?php echo "http://".URL_CONFIG."/public/data/connect/";?>'+file;
                                    url_logo='<?php echo "/public/data/connect/";?>'+file;
                                    var image="<img src='"+src+"'/>";
                                    var name="<br/>"+file;
                                    $('<li></li>').appendTo('#files').html(image+name).addClass('success');
                                } else{
                                    $('<li></li>').appendTo('#files').text(file).addClass('error');
                                }
                            }
                        });

                        });
                        </script>
                </div>

            </div>
            <div class="da-form-row">

                <label>Link:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqLink" id="link" />

                </div>

            </div>
            <div class="da-form-row">

                <label>Order:</label>

                <div class="da-form-item small">

                    <input type="text" name="reqOrder" id="order"/>

                </div>

            </div>
            <div class="da-form-row">
                <label>Status: </label>
                <div class="da-form-item small">
                    <select name="reqStatus" id="statuss">
                        <option value="1">Enable</option>
                        <option value="0">Disable</option>
                    </select>
                </div>
            </div>
            <div class="da-button-row">
                <input type="reset" value="Reset" id="reset_connect" class="da-button gray left" />
                <input type="submit" value="Add" class="da-button green" id="btn_add_connect" />
            </div>

        </div>

    </form>

</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#btn_add_connect").click(function(){
            var title = jQuery("#title").val();
            var link = jQuery("#link").val();
            var order = jQuery("#order").val();
            var status = jQuery("#statuss").val();
            var fullDate = new Date();                                          
            //convert month to 2 digits
            var twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : '0' + (fullDate.getMonth()+1);
              
            var dateModified = fullDate.getFullYear() + "-" + twoDigitMonth + "-" + fullDate.getDate();

            var datalist=new Array();
                datalist[0]= url_logo;
                datalist[1]= title;
                datalist[2]= link;
                datalist[3]= dateModified; 
                datalist[4]= order;
                datalist[5]= status;
            jQuery.ajax({
                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/addconnect",
                type:"POST",
                data:{data:datalist},
                success:function(result){
                    alert(result);
                }
            });
        });
        jQuery("#reset_connect").click(function(){
            if(url_logo!=""){
                var root_base='<?php echo ROOT_CONFIG;?>';
                var file = root_base+url_logo;
                jQuery.ajax({
                    url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deletefile",
                    type:"POST",
                    data:{data:file},
                    success:function(result){
                        jQuery("#files li").remove();
                    }
                });
            }
        });
    });
    
</script>

<!-- View Connect-->

<div id="dialog_view_connect" class="no-padding">
    <form id="da-ex-dialog-form-val" class="da-form">

        <div id="da-validate-error" class="da-message error" style="display:none;"></div>

        <div class="da-form-inline">

            <div class="da-form-row">

                <label>Title:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqTitle" id="view_title" />

                </div>

            </div>
            <div class="da-form-row">

                <label>Icon:</label>
                <div class="customfiles da-form-item large">
                    <img src="" style="width:480px; height:200px;" id="view_image">
                </div>

            </div>
            <div class="da-form-row">

                <label>Link:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqLink" id="view_link" />

                </div>

            </div>
            <div class="da-form-row">

                <label>Order:</label>

                <div class="da-form-item small">

                    <input type="text" name="reqOrder" id="view_order"/>

                </div>

            </div>
            <div class="da-form-row">
                <label>Status: </label>
                <div class="da-form-item small">
                    <select name="reqStatus" id="view_statuss">
                        <option value="1">Enable</option>
                        <option value="0">Disable</option>
                    </select>
                </div>
            </div>
        </div>

    </form>

</div>
<!-- View Connect-->

<div id="dialog_update_connect" class="no-padding">
    <form id="da-ex-dialog-form-val" class="da-form">

        <div id="da-validate-error" class="da-message error" style="display:none;"></div>

        <div class="da-form-inline">

            <div class="da-form-row">

                <label>Title:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqTitle" id="up_title" />

                </div>

            </div>
            <div class="da-form-row">

                <label>Icon:</label>
                <div class="customfiles da-form-item large">
                    <img src="" style="width:480px; height:200px; padding:0px 0px 20px 0px;" id="up_image">
                    <input type="file" id="file-upload-update" class=" da-custom-file customfile-input" style="left: -14px; top: 15px; ">

                        <span id="status" ></span>

                        <ul id="files-update" class="files"></ul>
                        <script type="text/javascript" >
                            var url_update_logo="";
                            $(function(){
                            var btnUpload=$('#file-upload-update');
                            var status=$('#status');
                            new AjaxUpload(btnUpload, {
                                action: '<?php echo "http://".URL_CONFIG."/public/admin/index/uploadiconconnect";?>',
                                name: 'uploadfile',
                                onSubmit: function(file, ext){
                                     if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){ 
                                        // extension is not allowed 
                                        status.text('Only JPG, PNG or GIF files are allowed');
                                        return false;
                                    }
                                    status.text('Uploading...');
                                },
                                onComplete: function(file, response){
                                    //On completion clear the status
                                    status.text('');
                                    //Add uploaded file to list
                                    if(response==="success"){
                                        var src='<?php echo "http://".URL_CONFIG."/public/data/connect/";?>'+file;
                                        url_update_logo='<?php echo "/public/data/connect/";?>'+file;
                                        var image="<img src='"+src+"'/>";
                                        var name="<br/>"+file;
                                        $('<li></li>').appendTo('#files-update').html(image+name).addClass('success');
                                    } else{
                                        $('<li></li>').appendTo('#files-update').text(file).addClass('error');
                                    }
                                }
                            });

                            });
                            </script>
                </div>

            </div>
            <div class="da-form-row">

                <label>Link:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqLink" id="up_link" />

                </div>

            </div>
            <div class="da-form-row">

                <label>Order:</label>

                <div class="da-form-item small">

                    <input type="text" name="reqOrder" id="up_order"/>

                </div>

            </div>
            <div class="da-form-row">
                <label>Status: </label>
                <div class="da-form-item small">
                    <select name="reqStatus" id="up_statuss">
                        <option value="1">Enable</option>
                        <option value="0">Disable</option>
                    </select>
                </div>
            </div>
            <div class="da-button-row">
                <input type="reset" value="Reset" id="reset_update_connect" class="da-button gray left" />
                <input type="button" value="Update" class="da-button green" id="btn_update_connect" />
            </div>
        </div>

    </form>

</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#btn_update_connect").click(function(){

            var title= jQuery("#up_title").val();
            var link = jQuery("#up_link").val();
            var order = jQuery("#up_order").val();
            var status = jQuery("#up_statuss").val();
            var image = "";
            if(url_update_logo==""){
                image="<?php echo $result['icon']; ?>";
            }else{
                image=url_update_logo;
            }
            
            var fullDate = new Date();                                          
            //convert month to 2 digits
            var twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : '0' + (fullDate.getMonth()+1);
              
            var dateModified = fullDate.getFullYear() + "-" + twoDigitMonth + "-" + fullDate.getDate();
            //alert(id_update);
            var datalist=new Array();
                datalist[0]= id_update;
                datalist[1]= image;
                datalist[2]= title;
                datalist[3]= link;
                datalist[4]= dateModified; 
                datalist[5]= order;
                datalist[6]= status;
            jQuery.ajax({
                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/updateconnect",
                type:"POST",
                data:{data:datalist},
                success:function(result){
                    
                    if(result=="true"){
                        jQuery("#up_title").val("");
                        jQuery("#up_image").attr('src',"");
                        jQuery("#up_link").val("");
                        jQuery("#up_order").val("");
                        jQuery("#up_statuss").val("");
                        image="";
                        id_update="";
                        alert("Update connect successfull");
                        location.href="<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/connect";
                    }else{
                        alert(result);
                        return;
                    }
                }
            });
        });
    });
    
</script>