<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                Edit Membership
                <a href="<?php echo $this->url(array ( 'action'=> 'membership','controller'=> 'index', 'module'=> 'admin') ); ?>" class="da-tooltip-sw da-button gray" id="da-ex-dialog-form" value="Back" original-title="Click here to back">Back</a>
            </span>
            
        </div>
        <?php $result = $this->membership[0]; ?>
        <div class="da-panel-content">

            <script type="text/javascript">
                jQuery(document).ready(function() {
                    jQuery("form#da-ex-dialog-form-val").validate({
                        rules:{
                            reqTitle:{required:true},
                            reqStatus:{required:true}},
                        invalidHandler:function(f,d){
                            var g=d.numberOfInvalids();
                            if(g){var e=g==1?"You missed 1 field. It has been highlighted":"You missed "+g+" fields. They have been highlighted";
                                jQuery("#da-validate-error").html(e).show()
                            }else{
                                jQuery("#da-validate-error").hide()
                            }
                        },
                        success: function(label) {
                             
                           },
                        submitHandler: function(form) {
                            var id = "<?php echo $result['id']; ?>";
                            var title = jQuery("#title").val();
                            var content = CKEDITOR.instances['editor'].getData();
                            var type = jQuery("#type").val();
                            var status = jQuery("#statuss").val();
                            var datalist=new Array();
                                datalist[0]= id;
                                datalist[1]= title;
                                datalist[2]= content; 
                                datalist[3]= type;
                                datalist[4]= status;
                            jQuery.ajax({
                                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/updatemembership",
                                type:"POST",
                                data:{data:datalist},
                                success:function(result){
                                    alert(result);
                                    form.submit();
                                }
                            });
                        }
                    });
                    var baseUrl = jQuery("#baseUrl").val();
                    CKEDITOR.replace( 'editor',{
                        filebrowserBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?id=demo3',
                        filebrowserImageBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Images&id=demo3',
                        filebrowserFlashBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Flash&id=demo3',
                        filebrowserUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserImageUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserFlashUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash&currentFolder=/Public%20Folder&id=demo3'
                    });
                });
            </script>
<div id="da-ex-dialog-form-div" class="no-padding">
    
    <form id="da-ex-dialog-form-val" class="da-form">

        <div id="da-validate-error" class="da-message error" style="display:none;"></div>

        <div class="da-form-inline">

            <div class="da-form-row">

                <label>Title:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqTitle" id="title" value="<?php echo $result['title'] ?>" />

                </div>

            </div>
            <div class="da-form-row">
                <label>Content:</label>

                <div class="da-form-item large">
                    <form class="da-form">
                        <div id="editor"><?php echo $result['content'] ?></div>
                    </form>

                </div>
                

            </div>
            <div class="da-form-row">
                <label>Type: </label>
                <div class="da-form-item small">
                    <select name="reqType" id="type">
                        <?php
                            if(count($this->typemembership)>0){
                                foreach ($this->typemembership as $type) {
                                    if($type['id']==$result['typeid']){
                                        echo "<option selected=\"selected\" value=\"".$type['id']."\">".$type['name']."</option>";
                                    }else{
                                        echo "<option value=\"".$type['id']."\">".$type['name']."</option>";
                                    }
                                }
                            }
                        ?>
                    </select>
                </div>
            </div>
            <div class="da-form-row">
                <label>Status: </label>
                <div class="da-form-item small">
                    <select name="reqStatus" id="statuss">
                        <?php
                            if($result['status']==1){
                                echo "<option selected=\"selected\" value=\"1\">Enable</option>
                        <option value=\"0\">Disable</option>";
                            }else{
                                echo "<option value=\"1\">Enable</option>
                        <option selected=\"selected\" value=\"0\">Disable</option>";
                            }
                        ?>
                        
                    </select>
                </div>
            </div>
            <div class="da-button-row">
                <input type="reset" value="Reset" class="da-button gray left">
                <input type="submit" value="Update" id="btn_update_about" class="da-button pink">
            </div>
        </div>

    </form>
</div>
        </div>
    </div>
</div>