<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                Edit Conferences
                <a href="<?php echo $this->url(array ( 'action'=> 'conferences','controller'=> 'index', 'module'=> 'admin') ); ?>" class="da-tooltip-sw da-button gray" id="da-ex-dialog-form" value="Back" original-title="Click here to back">Back</a>
            </span>
            
        </div>
        <?php $result = $this->conferences[0]; ?>
        <div class="da-panel-content">

            <script type="text/javascript">
                jQuery(document).ready(function() {
                    jQuery("form#da-ex-dialog-form-val").validate({
                        rules:{
                            reqTitle:{required:true},
                            reqDescription:{required:true},
                            reqStartdate:{required:true},
                            reqEnddate:{required:true},
                            reqContact:{required:true},
                            reqLocation:{required:true},
                            reqStatus:{required:true}},
                        invalidHandler:function(f,d){
                            var g=d.numberOfInvalids();
                            if(g){var e=g==1?"You missed 1 field. It has been highlighted":"You missed "+g+" fields. They have been highlighted";
                                jQuery("#da-validate-error").html(e).show()
                            }else{
                                jQuery("#da-validate-error").hide()
                            }
                        },
                        success: function(label) {
                             
                           },
                        submitHandler: function(form) {
                            var id = "<?php echo $result['id']; ?>";
                            var title = jQuery("#title").val();
                            var image = "";
                            if(url_logo==""){
                                image = "<?php echo $result['image']; ?>";
                            }else{
                                image=url_logo;
                            }
                            var description = jQuery("#description").val();
                            var content = CKEDITOR.instances['editor'].getData();
                            var start_date = jQuery("#start_date").val();
                            var end_date = jQuery("#end_date").val();
                            var location = jQuery("#location").val();
                            var contact = jQuery("#contact").val();
                            var status = jQuery("#statuss").val();
                            var fullDate = new Date();                                          
                            //convert month to 2 digits
                            var twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : '0' + (fullDate.getMonth()+1);
                              
                            var dateModified = fullDate.getFullYear() + "-" + twoDigitMonth + "-" + fullDate.getDate();
                            var datalist=new Array();
                                datalist[0]= id;
                                datalist[1]= title;
                                datalist[2]= image; 
                                datalist[3]= description;
                                datalist[4]= content;
                                datalist[5]= start_date;
                                datalist[6]= end_date;  
                                datalist[7]= location;  
                                datalist[8]= contact;  
                                datalist[9]= status; 
                            jQuery.ajax({
                                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/updateconferences",
                                type:"POST",
                                data:{data:datalist},
                                success:function(result){
                                    alert(result);
                                    form.submit();
                                }
                            });
                        }
                    });
                    var baseUrl = jQuery("#baseUrl").val();
                    CKEDITOR.replace( 'editor',{
                        filebrowserBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?id=demo3',
                        filebrowserImageBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Images&id=demo3',
                        filebrowserFlashBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Flash&id=demo3',
                        filebrowserUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserImageUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserFlashUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash&currentFolder=/Public%20Folder&id=demo3'
                    });
                });
            </script>
<div id="da-ex-dialog-form-div" class="no-padding">
    
    <form id="da-ex-dialog-form-val" class="da-form">

        <div id="da-validate-error" class="da-message error" style="display:none;"></div>

        <div class="da-form-inline">

            <div class="da-form-row">

                <label>Title:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqTitle" id="title" value="<?php echo $result['title'] ?>" />

                </div>

            </div>
            <div class="da-form-row">
                <label>Image:</label>
                <div class="da-form-item large">
                    <img src="<?php echo 'http://'.URL_CONFIG.$result['image']; ?>" style="width:300px; height:200px; padding:0px 0px 20px 0px;">
                    <input type="file" id="file-upload" class=" da-custom-file customfile-input" style="left: -14px; top: 15px; ">

                    <span id="status" ></span>

                    <ul id="files" ></ul>
                    <script type="text/javascript" >
                        var url_logo="";
                        $(function(){
                        var btnUpload=$('#file-upload');
                        var status=$('#status');
                        var folder="<?php echo ROOT_CONFIG.'/public/data/news/'?>";
                        new AjaxUpload(btnUpload, {
                            action: '<?php echo "http://".URL_CONFIG."/public/admin/index/uploadimagenews";?>',
                            name: 'uploadfile',
                            onSubmit: function(file, ext){
                                 if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){ 
                                    // extension is not allowed 
                                    status.text('Only JPG, PNG or GIF files are allowed');
                                    return false;
                                }
                                status.text('Uploading...');
                            },
                            onComplete: function(file, response){
                                //On completion clear the status
                                status.text('');
                                //Add uploaded file to list
                                if(response==="success"){
                                    var src='<?php echo "http://".URL_CONFIG."/public/data/news/";?>'+file;
                                    url_logo='<?php echo "/public/data/news/";?>'+file;
                                    var image="<img src='"+src+"'/>";
                                    var name="<br/>"+file;
                                    $('<li></li>').appendTo('#files').html(image+name).addClass('success');
                                } else{
                                    $('<li></li>').appendTo('#files').text(file).addClass('error');
                                }
                            }
                        });

                        });
                        </script>
                </div>
            </div>
            <div class="da-form-row">

                <label>Description:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqDescription" id="description"  value="<?php echo $result['description'] ?>"/>

                </div>

            </div>
            <div class="da-form-row">
                <label>Content:</label>

                <div class="da-form-item large">
                    <form class="da-form">
                        <div id="editor"><?php echo $result['content'] ?></div>
                    </form>

                </div>
                

            </div>
            <div class="da-form-row">

                <label>Start date:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqStartdate" id="start_date" value="<?php echo $result['start_date'] ?>"/>

                </div>

            </div>
            <div class="da-form-row">

                <label>End date:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqEnddate" id="end_date" value="<?php echo $result['end_date'] ?>"/>

                </div>

            </div>
            <div class="da-form-row">

                <label>Location:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqLocation" id="location" value="<?php echo $result['location'] ?>"/>

                </div>

            </div>
            <div class="da-form-row">

                <label>Contact:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqContact" id="contact" value="<?php echo $result['contact'] ?>"/>

                </div>

            </div>
            <div class="da-form-row">
                <label>Status: </label>
                <div class="da-form-item small">
                    <select name="reqStatus" id="statuss">
                        <?php
                            if($result['status']==1){
                                echo "<option selected=\"selected\" value=\"1\">Enable</option>
                        <option value=\"0\">Disable</option>";
                            }else{
                                echo "<option value=\"1\">Enable</option>
                        <option selected=\"selected\" value=\"0\">Disable</option>";
                            }
                        ?>
                    </select>
                </div>
            </div>
            <div class="da-button-row">
                <input type="reset" value="Reset" class="da-button gray left">
                <input type="submit" value="Update" id="btn_update_about" class="da-button pink">
            </div>
        </div>

    </form>
</div>
        </div>
    </div>
</div>