        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="components/flot/excanvas.min.js"></script><![endif]-->
        
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/js/domain.js"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/ui/jquery.ui.min.js"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/ui/jquery.autotab.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/ui/timepicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/colorpicker/js/colorpicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/checkboxes/iphone.check.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/elfinder/js/elfinder.full.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/datatables/dataTables.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/scrolltop/scrolltopcontrol.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/fancybox/jquery.fancybox.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/jscrollpane/mousewheel.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/jscrollpane/mwheelIntent.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/jscrollpane/jscrollpane.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/spinner/ui.spinner.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/tipsy/jquery.tipsy.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/editor/jquery.cleditor.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/chosen/chosen.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/confirm/jquery.confirm.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/validationEngine/jquery.validationEngine.js" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/validationEngine/jquery.validationEngine-en.js" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/vticker/jquery.vticker-min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/sourcerer/sourcerer.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/fullcalendar/fullcalendar.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/flot/flot.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/flot/flot.pie.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/flot/flot.resize.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/flot/graphtable.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/uploadify/swfobject.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/uploadify/uploadify.js"></script>        
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/checkboxes/customInput.jquery.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/effect/jquery-jrumble.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/filestyle/jquery.filestyle.js" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/placeholder/jquery.placeholder.js" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/Jcrop/jquery.Jcrop.js" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/imgTransform/jquery.transform.js" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/webcam/webcam.js" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/rating_star/rating_star.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/dualListBox/dualListBox.js"  ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/smartWizard/jquery.smartWizard.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/js/jquery.cookie.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/admin/system/components/js/zice.custom.js"></script>
        
        <script type="text/javascript">
        jQuery(document).ready(function() {
            var base_url=jQuery("#baseUrl").val();
            var base_root=jQuery("#documentRoot").val();
            $('#uploadify').uploadify({
              'uploader'  : 'http://'+base_url+'/public/templates/admin/system/components/uploadify/uploadify.swf',
              'script'    : 'http://'+base_url+'/public/templates/admin/system/components/uploadify/uploadify.php',
              'cancelImg' : 'http://'+base_url+'/public/templates/admin/system/components/uploadify/cancel.png',
              'folder'    : 'uploads',
              'method'  : 'GET',
              'multi': true, 'auto': false,'fileExt': '*.jpg;*.gif;*.png','fileDesc': 'Image Files (.JPG, .GIF, .PNG)',
              'queueID'        : 'custom-queue',
              'wmode'       : 'transparent',
              'hideButton': true,
              'width': 92,'height': 26,
              'sizeLimit'   : parseInt($('#maxUploadFileSize').text()),
                  'onClearQueue' : function(event) {
                      $('#upload_c').removeClass('special').addClass('disable');
                      $('#uploadFile').removeClass('uploadFile confirm ').addClass('disable');   
                      $('#status-message').html(' ');
                    },
                'onSelectOnce'   : function(event,data) {
                      $('#upload_c').removeClass('disable').addClass('special');
                      $('#uploadButtondisable').css({'display':'none'});
                      $('#uploadFile').removeClass('disable').addClass('uploadFile confirm ');   
                      $('#status-message').html('Ready');
                    },
                  'onAllComplete'  : function(event,data) {
                  if(data.errors){
                                $('#status-message').html('Complete '+ data.filesUploaded + ' file , <font color=red>and ' + data.errors + ' file donot Complete </font>.');
                                showError('uploadComplete'+ data.filesUploaded + 'file , <font color=red>and ' + data.errors + ' file donot Complete </font>.',7000);
                                
                          }else{
                                  $('#status-message').html('Complete '+ data.filesUploaded + ' file');
                                  showSuccess('uploadComplete '+ data.filesUploaded  +' File',7000);
                                  setTimeout('$.fancybox.close()',1500);  // uploadmodal with close  ;
                         }
                    }
                }); 

        });
        
        </script>
<div class="onecolumn noborder" >
    <div class="header border">
        <span>
            <span class="ico gray file"></span>
            FILE Manager Callback
        </span>
    </div>
    <!-- End header -->
    <div class="clear"></div>
    <div id="finder">finder</div>
</div>

<div class="clear"></div>

<div class="onecolumn" >
    <div class="header">
        <span>
            <span class="ico  gray  folder"></span>
            FILE Manager Callback
        </span>
        <div id="buttom_top">
            <ul class="uibutton-group">
                <li>
                    <a class="uibutton   add icon  special" id="filemanager" href="#" title='fileimport'>filemanager modal</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- End header -->
    <br class="clear"/>
    <div class="content" >
        <!--/start TAB/-->
        <div id="uploadTab">
            <ul class="tabs" >
                <li >
                    <a href="#tab1">input callback</a>
                </li>
            </ul>
            <div class="tab_container" >
                <div id="tab1" class="tab_content">
                    <div class="load_page">
                        <div style="margin-left:25px">
                            <form  id="add" action="#">
                                <div class="section">
                                    <label>
                                        focus
                                        <small>
                                            Input  " <strong>focus</strong>
                                            " to call
                                        </small>
                                    </label>
                                    <div>
                                        <input type="text" name="menu" id="menu"  class="large fileDialog"  title="fileimport" />
                                        <span class="f_help">
                                            Title= <strong>&quot;fileimport&quot;</strong>
                                        </span>
                                    </div>
                                </div>
                                <div class="section ">
                                    <label>
                                        focus
                                        <small>
                                            Call filepart  with   "
                                            <strong>title</strong>
                                            "
                                        </small>
                                    </label>
                                    <div>
                                        <input type="text" name="menu_link" id="menu_link"   class="medium fileDialog" title="icon" />
                                        <span class="f_help">
                                            Title=
                                            <strong>&quot;icon&quot;</strong>
                                        </span>
                                    </div>
                                </div>
                                <div class="section ">
                                    <label>
                                        icon
                                        <small>
                                            "
                                            <strong>Click</strong>
                                            " to call
                                        </small>
                                    </label>
                                    <div>
                                        <input type="text" name="menu_icon" id="menu_icon" class="small"   />
                                        <a id="open_icon" title="icon"  rel="menu_icon" >open</a>
                                        <span class="f_help">Custom icon</span>
                                    </div>
                                </div>
                                <!--<div class="section last">
                                    <div>
                                        <a class="uibutton loading"  title="Saving"  rel="1">Submit</a>
                                        <a class="uibutton special "   onclick="$('#add').get(0).reset();" title="Reset  Form"   >Clear Form</a>
                                        <a class="uibutton confirm loading"  title="Checking"  rel="0">check</a>
                                    </div>
                                </div>-->
                            </form>
                        </div>
                    </div>
                </div>
                <!--tab1--> </div>
        </div>
        <!--/END TAB/-->
        <div class="clear"></div>
    </div>
</div>
<!-- // onecolumn -->