<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                News Management
                <a href="<?php echo $this->url(array ( 'action'=> 'addnews','controller'=> 'index', 'module'=> 'admin') ); ?>" class="da-tooltip-sw da-button gray" id="da-ex-dialog-form" value="Add new" original-title="Click here to add new a news">Add new</a>
            </span>
            
        </div>
        <div class="da-panel-content">
            <table id="da-ex-datatable-numberpaging" class="da-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Title</th>
                        <th>Order</th>
                        <th>Status</th>
                        <th>Type</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        if(count($this->data)>0){
                            foreach ($this->data as $result){
                                echo "<tr>";
                                    echo "<td>".$result['id']."</td>";
                                    echo "<td>".$result['title']."</td>";
                                    echo "<td>".$result['order']."</td>";
                                    if($result['status']==1){
                                        echo "<td> Enable</td>";
                                    }else{
                                        echo "<td> Disable</td>";
                                    }
                                    echo "<td>".$result['typeName']."</td>";
                                    echo "<td class=\"da-icon-column\">";
                                        echo "<a href=\"". $this->url(array ( 'action'=> 'viewnews','controller'=> 'index', 'module'=> 'admin','id'=>$result['id']))."\" id=\"".$result['id']."\" class=\"view_news\"><img src=\"images/icons/color/magnifier.png\" /></a>";
                                        echo "<a href=\"". $this->url(array ( 'action'=> 'editnews','controller'=> 'index', 'module'=> 'admin','id'=>$result['id']))."\" id=\"".$result['id']."\" class=\"edit_news\"><img src=\"images/icons/color/pencil.png\" /></a>";
                                        echo "<a href=\"#\" id=\"".$result['id']."\" class=\"delete_news\"><img src=\"images/icons/color/cross.png\" /></a>";
                                    echo "</td>";
                                echo "</tr>";                                
                            }
                        }
                     ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(".delete_news").click(function(evt){
            evt.preventDefault();
            var id = jQuery(this).attr("id");
            jQuery.ajax({
                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deletenews",
                type:"POST",
                data:{data:id},
                success:function(result){
                    if(result=="true"){
                        alert("Delete news successfull");
                        location.href="<?php echo 'http://'.URL_CONFIG.'/public/admin/index/news' ?>";
                    }else{
                        alert(result);
                        return;
                    }
                }
            });
        });
    });
    
</script>