<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                Publications Management
                <a href="<?php echo $this->url(array ( 'action'=> 'addpublications','controller'=> 'index', 'module'=> 'admin') ); ?>" class="da-tooltip-sw da-button gray" id="da-ex-dialog-form" value="Add new" original-title="Click here to add new">Add new</a>
            </span>
            
        </div>
        <div class="da-panel-content">
            <table id="da-ex-datatable-numberpaging" class="da-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Title</th>
                        <th>Start</th>
                        <th>End</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        if(count($this->data)>0){
                            foreach ($this->data as $result){
                                echo "<tr>";
                                    echo "<td>".$result['id']."</td>";
                                    echo "<td>".$result['title']."</td>";
                                    echo "<td>".$result['start_date']."</td>";
                                    echo "<td>".$result['end_date']."</td>";
                                    echo "<td class=\"da-icon-column\">";
                                        echo "<a href=\"".$this->url(array ( 'action'=> 'viewpublications','controller'=> 'index', 'module'=> 'admin','id'=>$result['id']))."\"><img src=\"images/icons/color/magnifier.png\" /></a>";
                                        echo "<a href=\"".$this->url(array ( 'action'=> 'editpublications','controller'=> 'index', 'module'=> 'admin','id'=>$result['id']))."\"><img src=\"images/icons/color/pencil.png\" /></a>";
                                        echo "<a href=\"#\" class=\"delete_publications\" id=\"".$result['id']."\"><img src=\"images/icons/color/cross.png\" /></a>";
                                    echo "</td>";
                                echo "</tr>";                                
                            }
                        }
                     ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(".delete_publications").click(function(){
            var choose = confirm("You are want to delete?");
            if(choose){
                var id = jQuery(this).attr("id");
                jQuery.ajax({
                    url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deletepublications",
                    type:"POST",
                    data:{data:id},
                    success:function(result){
                        if(result=="true"){
                            alert("Delete publications successfull");
                            location.href="<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/publications";
                        }else{
                            alert(result);
                            return;
                        }
                    }
                });
            }
        });
    });
    
</script>