<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                Setting Management
                <?php $result = $this->data[0]; ?>
            </span>            
        </div>
        <div class="da-panel-content">
                <form class="da-form">
                    <input type="hidden" value="<?php echo $result['id']; ?>" id="ID_setting"/>
                    <input type="hidden" value="<?php echo $result['logo']; ?>" id="logo_default"/>
                    <div class="da-form-row">
                        <div class="avatar" id="avatar" style="text-align:center;padding-bottom:20px;"><img src="<?php echo "http://".URL_CONFIG. $result['logo']; ?>" width="140" height="150"/></div>
                        <label>Logo:</label>
                        <div class="customfiles da-form-item large">
                            <input type="file" id="file-upload" class=" da-custom-file customfile-input" style="left: -14px; top: 15px; ">

                            <span id="status" ></span>
        
                            <ul id="files" ></ul>
                            <script type="text/javascript" >
                                var url_logo="";
                                $(function(){
                                var btnUpload=$('#file-upload');
                                var status=$('#status');
                                new AjaxUpload(btnUpload, {
                                    action: '<?php echo "http://".URL_CONFIG."/public/admin/index/uploadfile";?>',
                                    name: 'uploadfile',
                                    onSubmit: function(file, ext){
                                         if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){ 
                                            // extension is not allowed 
                                            status.text('Only JPG, PNG or GIF files are allowed');
                                            return false;
                                        }
                                        status.text('Uploading...');
                                    },
                                    onComplete: function(file, response){
                                        //On completion clear the status
                                        status.text('');
                                        //Add uploaded file to list
                                        if(response==="success"){
                                            var src='<?php echo "http://".URL_CONFIG."/public/data/logo/";?>'+file;
                                            url_logo='<?php echo "/public/data/logo/";?>'+file;
                                            var image="<img src='"+src+"'/>";
                                            var name="<br/>"+file;
                                            $('<li></li>').appendTo('#files').html(image+name).addClass('success');
                                        } else{
                                            $('<li></li>').appendTo('#files').text(file).addClass('error');
                                        }
                                    }
                                });

                                });
                                </script>
                                <script type="text/javascript">
                                jQuery(document).ready(function() {
                                    var url_base='<?php echo "http://".URL_CONFIG;?>';
                                    var root_base='<?php echo ROOT_CONFIG;?>';
                                    //Reset avatar
                                    jQuery("#reset_avatar").click(function(){
                                        var src=jQuery("#files li img").attr("src");
                                        if(typeof src === "undefined"){

                                        }else{
                                            jQuery.ajax({
                                                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deleteavatar",
                                                type:"POST",
                                                data:{root_base:root_base,avatar:url_logo},
                                                success:function(string){
                                                    alert(string);
                                                    jQuery("#files").remove();
                                                }
                                            });
                                        }
                                    });


                                    //Update avatar
                                    jQuery("#btn_update_avatar").click(function(){
                                        if(url_logo!=""){
                                            var id=jQuery("#ID_user").val();
                                            jQuery.ajax({
                                                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/updateavatar",
                                                type:"POST",
                                                data:{id:id,avatar:url_logo},
                                                success:function(string){
                                                    var data=jQuery.parseJSON(string);
                                                    if(data.check=="true" && data.url!=""){
                                                        alert("Update logo successfull");
                                                        jQuery("#files").remove();
                                                        jQuery('#avatar img').attr('src',url_base+data.url);
                                                    }else{
                                                        alert("Update logo successfull");
                                                    }
                                                }
                                            });
                                        }
                                    });
                                });
                                
                                </script>
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Company:</label>
                        <div class="da-form-item large">
                            <input type="text" id="company" value="<?php echo $result['company']; ?>" />
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Address:</label>
                        <div class="da-form-item large">
                            <input type="text" id="address" value="<?php echo $result['address']; ?>" />
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Email:</label>
                        <div class="da-form-item large">
                            <input type="text" id="email" value="<?php echo $result['email']; ?>" />
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Phone:</label>
                        <div class="da-form-item large">
                            <input type="text" id="phone" value="<?php echo $result['telephone']; ?>" />
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Fax:</label>
                        <div class="da-form-item large">
                            <input type="text" id="fax" value="<?php echo $result['fax']; ?>" />
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Website:</label>
                        <div class="da-form-item large">
                            <input type="text" id="website" value="<?php echo $result['website']; ?>" />
                        </div>
                    </div>
                    <div class="da-form-row da-form-block">
                        <label>Description:</label>
                        <div class="da-form-item large">
                            <div id="editor" name="editor"><?php echo $result['description']; ?></div>
                        </div>
                    </div>                    
                    <div class="da-button-row">
                        <input type="reset" value="Reset" id="reset_setting" class="da-button gray left" />
                        <input type="submit" value="Submit" class="da-button green" id="btn_update_setting" />
                    </div>
                    <script type="text/javascript" language="javascript">
                        jQuery(document).ready(function() {
                            jQuery("#btn_update_setting").click(function(){
                                var datalist=new Array();
                                var logo="";
                                if(url_logo==""){
                                    logo=jQuery("#logo_default").val();
                                }else{
                                    logo=url_logo;
                                }
                                datalist[0]= jQuery("#company").val();
                                datalist[1]=CKEDITOR.instances['editor'].getData(); 
                                datalist[2]=  logo;             
                                datalist[3]=jQuery("#address").val();
                                datalist[4]=jQuery("#email").val();  
                                datalist[5]=jQuery("#phone").val();
                                datalist[6]=jQuery("#fax").val();
                                datalist[7]=jQuery("#website").val();          
                                jQuery.ajax({
                                    url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/updatesetting",
                                    type:"POST",
                                    data:{data:datalist},
                                    success:function(result){
                                        alert(result);
                                    }
                                });

                            });
                            jQuery("#reset_setting").click(function(){
                                if(url_logo!=""){
                                    var root_base='<?php echo ROOT_CONFIG;?>';
                                    var file = root_base+url_logo;
                                    jQuery.ajax({
                                        url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deletefile",
                                        type:"POST",
                                        data:{data:file},
                                        success:function(result){
                                            jQuery("#files li").remove();
                                        }
                                    });
                                }
                            });
                        });
                        
                    </script>   
                </form>
            </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("form.da-form").validate({
            rules:{
                reqOrder:{required:true,digits:true},
                reqStatus:{required:true}},
            invalidHandler:function(f,d){
                var g=d.numberOfInvalids();
                if(g){var e=g==1?"You missed 1 field. It has been highlighted":"You missed "+g+" fields. They have been highlighted";
                    jQuery("#da-validate-error").html(e).show()
                }else{
                    jQuery("#da-validate-error").hide()
                }
            }
        });

        var baseUrl = jQuery("#baseUrl").val();
        CKEDITOR.replace( 'editor',{
            filebrowserBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?id=demo3',
            filebrowserImageBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Images&id=demo3',
            filebrowserFlashBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Flash&id=demo3',
            filebrowserUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&currentFolder=/Public%20Folder&id=demo3',
            filebrowserImageUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&currentFolder=/Public%20Folder&id=demo3',
            filebrowserFlashUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash&currentFolder=/Public%20Folder&id=demo3'
        });
    });
    
</script>