<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                User Management
                <a href="<?php echo $this->url(array ( 'action'=> 'adduser','controller'=> 'index', 'module'=> 'admin') ); ?>" class="da-tooltip-sw da-button gray" id="add_new_user" value="Add new" original-title="Click here to add new user">Add new user</a>
                
            </span>
            
        </div>
        <div class="da-panel-content">
            <table id="da-ex-datatable-numberpaging" class="da-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Company</th>
                        <th>Phone</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        if(count($this->data)>0){
                            foreach ($this->data as $result){
                                echo "<tr>";
                                    echo "<td>".$result['id']."</td>";
                                    echo "<td>".$result['company']."</td>";
                                    echo "<td>".$result['phone']."</td>";
                                    if($result['status']==1)
                                        echo "<td>Enable</td>";
                                    else
                                        echo "<td>Disable</td>";
                                    echo "<td class=\"da-icon-column\">";
                                        echo "<a href=\"".$this->url(array ( 'action'=> 'viewuser','controller'=> 'index', 'module'=> 'admin','id'=>$result['id']) )."\"><img src=\"images/icons/color/magnifier.png\" /></a>";
                                        echo "<a href=\"".$this->url(array ( 'action'=> 'edituser','controller'=> 'index', 'module'=> 'admin','id'=>$result['id']) )."\"><img src=\"images/icons/color/pencil.png\" /></a>";
                                        echo "<a href=\"#\" class=\"deleteuser\" id=\"".$result['id']."\"><img src=\"images/icons/color/cross.png\" /></a>";
                                    echo "</td>";
                                echo "</tr>";                                
                            }
                        }
                     ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(".deleteuser").click(function(evt){
            evt.preventDefault();
            var choose = confirm("You are want to delete?");
            if(choose){
                var id = jQuery(this).attr('id');
                jQuery.ajax({
                    url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deleteuser",
                    type:"POST",
                    data:{id:id},
                    success:function(result){
                        if(result=="true"){
                            alert("Delete account successfull");
                            location.href="<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/user";
                        }else{
                            alert(result);
                            return;
                        }
                                            
                    }
                });
            }
        });
    });
    
</script>