<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                View Community
                <a href="<?php echo $this->url(array ( 'action'=> 'community','controller'=> 'index', 'module'=> 'admin') ); ?>" class="da-tooltip-sw da-button gray" id="da-ex-dialog-form" value="Back" original-title="Click here to back">Back</a>
            </span>
            
        </div>
        <div class="da-panel-content">

            <script type="text/javascript">
                jQuery(document).ready(function() {
                    jQuery("#da-ex-dialog-form").bind("click",function(d){
                        jQuery("#da-ex-dialog-form-div").dialog("option",{modal:true}).dialog("open");
                        d.preventDefault();
                    });
                    var baseUrl = jQuery("#baseUrl").val();
                    CKEDITOR.replace( 'content',{
                        filebrowserBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?id=demo3',
                        filebrowserImageBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Images&id=demo3',
                        filebrowserFlashBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Flash&id=demo3',
                        filebrowserUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserImageUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserFlashUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash&currentFolder=/Public%20Folder&id=demo3'
                    });
                    CKEDITOR.replace( 'description',{
                        filebrowserBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?id=demo3',
                        filebrowserImageBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Images&id=demo3',
                        filebrowserFlashBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Flash&id=demo3',
                        filebrowserUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserImageUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserFlashUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash&currentFolder=/Public%20Folder&id=demo3'
                    });
                });
            </script>

<?php $result = $this->community[0]; ?>
<div id="da-ex-dialog-form-div" class="no-padding">
    <form id="da-ex-dialog-form-val" class="da-form">

        <div id="da-validate-error" class="da-message error" style="display:none;"></div>

        <div class="da-form-inline">

            <div class="da-form-row">

                <label>Title:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqName" id="title" value="<?php echo $result['title']; ?>"/>

                </div>

            </div>
            <div class="da-form-row">

                <label>Link:</label>

                <div class="da-form-item large">

                    <input type="text" name="reqLink" id="link" value="<?php echo $result['link']; ?>" />

                </div>

            </div>
            <div class="da-form-row">

                <label>Description:</label>

                <div class="da-form-item large">

                    <div id="description"><?php echo $result['description']; ?></div>

                </div>

            </div>
            <div class="da-form-row">
                <label>Content:</label>

                <div class="da-form-item large">
                    <form class="da-form">

                        <div id="content"><?php echo $result['content']; ?></div>
                    </form>

                </div>
                

            </div>
            <div class="da-form-row">
                <label>Author:</label>
                <div class="da-form-item small">
                    <input type="text" name="reqAuthor" id="author" value="<?php echo $result['author']; ?>" />
                </div>
            </div>
            <div class="da-form-row">
                <label>Type: </label>
                <div class="da-form-item small">
                    <select name="reqType" id="type">
                        <?php
                            if(count($this->typecommunity)>0){
                                foreach ($this->typecommunity as $type) {
                                    if($result['typeid']==$type['id']){
                                        echo "<option selected=\"selected\" value=\"".$type['id']."\">".$type['name']."</option>";
                                    }else{
                                        echo "<option value=\"".$type['id']."\">".$type['name']."</option>";
                                    }
                                    
                                }
                            }
                        ?>
                    </select>
                </div>
            </div>
            <div class="da-form-row">
                <label>Status: </label>
                <div class="da-form-item small">
                    <select name="reqStatus" id="statuss">
                        <?php 
                            if($result['status']==1){
                                echo "<option selected=\"selected\"  value=\"1\">Enable</option>
                        <option value=\"0\">Disable</option>";
                            }else{
                                echo "<option value=\"1\">Enable</option>
                        <option selected=\"selected\" value=\"0\">Disable</option>";
                            }
                        ?>
                        
                    </select>
                </div>
            </div>
        </div>

    </form>
</div>
        </div>
    </div>
</div>