<div class="grid_4">
    <div class="da-panel collapsible">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="images/icons/black/16/computer_imac.png" alt="Panel" />
                View News
                <a href="<?php echo $this->url(array ( 'action'=> 'news','controller'=> 'index', 'module'=> 'admin') ); ?>" class="da-tooltip-sw da-button gray" id="da-ex-dialog-form" value="Back" original-title="Click here to back">Back</a>
            </span>

        </div>
        <div class="da-panel-content">

            <script type="text/javascript">
                jQuery(document).ready(function() {
                    var baseUrl = jQuery("#baseUrl").val();
                    CKEDITOR.replace( 'content',{
                        filebrowserBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?id=demo3',
                        filebrowserImageBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Images&id=demo3',
                        filebrowserFlashBrowseUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/ckfinder.html?Type=Flash&id=demo3',
                        filebrowserUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserImageUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&currentFolder=/Public%20Folder&id=demo3',
                        filebrowserFlashUploadUrl : 'http://'+baseUrl+'/public/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash&currentFolder=/Public%20Folder&id=demo3'
                    });
                });
            </script>
            <?php $result=$this->data[0]; ?>
            <div id="da-ex-dialog-form-div" class="no-padding">
                <form id="da-ex-dialog-form-val" class="da-form">

                    <div id="da-validate-error" class="da-message error" style="display:none;"></div>

                    <div class="da-form-inline">

                        <div class="da-form-row">

                            <label>Title:</label>

                            <div class="da-form-item large">

                                <input type="text" name="reqTitle" value="<?php echo $result['title']; ?>" id="title" disabled="disabled" />

                            </div>

                        </div>
                        <div class="da-form-row">
                            <label>Image:</label>
                            <div class="da-form-item large">
                                <img src="<?php echo $result['image']; ?>" style="width:480px;height:200px"/>
                            </div>
                        </div>
                        <div class="da-form-row">
                            <label>Description:</label>

                            <div class="da-form-item large">
                                <textarea id="description" name="description"><?php echo $result['description']; ?></textarea>
                            </div>

                        </div>
                        <div class="da-form-row">
                            <label>Content:</label>

                            <div class="da-form-item large">
                                <form class="da-form">

                                    <div id="content" name="content" id="content"><?php echo $result['content']; ?></div>
                                </form>

                            </div>

                        </div>
                        <div class="da-form-row">

                            <label>Link:</label>

                            <div class="da-form-item large">

                                <input type="text" name="reqLink" value="<?php echo $result['link']; ?>" id="link" />

                            </div>

                        </div>

                        <div class="da-form-row">

                            <label>Author:</label>

                            <div class="da-form-item large">

                                <input type="text" name="reqAuthor" value="<?php echo $result['author']; ?>" id="author" />

                            </div>

                        </div>
                        <div class="da-form-row">
                            <label>Type news:</label>
                            <div class="da-form-item small">
                                <select name="reqTypenews" id="typeNews">
                                    <option><?php
                                        echo $result['typeName'];
                                     ?></option>
                                </select>
                            </div>
                        </div>
                        <div class="da-form-row">

                            <label>Order:</label>

                            <div class="da-form-item small">

                                <input type="text" name="reqOrder" value="<?php echo $result['order']; ?>" id="order"/>

                            </div>

                        </div>
                        <div class="da-form-row">
                            <label>Status:</label>
                            <div class="da-form-item small">
                                <select name="reqStatus" id="statuss">
                                    <option><?php 
                                        if($result['status']==1){
                                            echo "Enable";
                                        }else{
                                            echo "Disable";
                                        }
                                    ?></option>
                                </select>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#btn_add_news").click(function(){
            var title = jQuery("#title").val();
            var image = url_logo;
            var des = CKEDITOR.instances['description'].getData();
            var content = CKEDITOR.instances['content'].getData();
            var link = jQuery("#link").val();
            var author = jQuery("#author").val();
            var typeNews = jQuery("#typeNews").val();
            var order = jQuery("#order").val();
            var status = jQuery("#statuss").val();
            var fullDate = new Date();                                          
            //convert month to 2 digits
            var twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : '0' + (fullDate.getMonth()+1);
              
            var dateModified = fullDate.getFullYear() + "-" + twoDigitMonth + "-" + fullDate.getDate();
            var datalist=new Array();
                datalist[0]= title;
                datalist[1]= des; 
                datalist[2]= content;
                datalist[3]= dateModified;
                datalist[4]= image;
                datalist[5]= typeNews;  
                datalist[6]= link;  
                datalist[7]= author;  
                datalist[8]= order; 
                datalist[9]= status;
            jQuery.ajax({
                url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/savenews",
                type:"POST",
                data:{data:datalist},
                success:function(result){
                    alert(result);
                }
            });
        });
        jQuery("#btn_reset").click(function(){
            if(url_logo!=""){
                var root_base='<?php echo ROOT_CONFIG;?>';
                var file = root_base+url_logo;
                jQuery.ajax({
                    url:"<?php echo 'http://'.URL_CONFIG;?>/public/admin/index/deletefile",
                    type:"POST",
                    data:{data:file},
                    success:function(result){
                        jQuery("#files li").remove();
                    }
                });
            }
        });
    });
    
</script>