<div id="da-wrapper" class="fluid">
    
        <!-- Content -->
        <div id="da-content">
            
            <!-- Container -->
            <div class="da-container clearfix">
            
            	<div id="da-error-wrapper">
                	
                   	<div id="da-error-pin"></div>
                    <div id="da-error-code">
                    	error <span>404</span>
                    </div>
                
                	<h1 class="da-error-heading">Whoops, it seems you are lost</h1>
                    <p>Please allow us to guide you out of this place by following <a href="<?php echo $this->url(array ('controller'=> 'index', 'action'=> 'index', 'module'=> 'admin') ) ?>">this link</a></p>
                </div>
            
            </div>
            
        </div>
        
        <!-- Footer -->
        <div id="da-footer">
        	<div class="da-container clearfix">
            	<p>Copyright 2012. <a href="#">AATI company</a>. All Rights Reserved.
            </div>
        </div>
        
    </div>
