<?php require("common.php"); ?>
<div id="breadcrumb">
    <ul>
        <li><a href="<?php echo $this->url(array ( 'action'=> 'index','controller'=> 'index', 'module'=> 'default'),null,true )?>" title="Home">Home</a></li>
        <li class="separate"></li>
        <li><a href="<?php echo $this->url(array ( 'action'=> 'about','controller'=> 'index', 'module'=> 'default'),null,true )?>" title="About">About</a></li>
        <li class="separate"></li>
        <li class="current"><a href="" title="<?php echo $this->data[0]['name'];?>"><?php echo splitString($this->data[0]['name'],30); ?></a></li>
    </ul>
</div>
<div class="content_news_left fl">
    <div id="about">
        <div class="title_block_about"><span class="text">DETAIL ABOUT
        </span></div>
        
        <div class="content_block_news_detail">
            <?php
                if(isset($this->data) && count($this->data)>0){
                    $result=$this->data[0];
                ?>
                    <div class="title_news"><?php echo $result['name']; ?></div>
                    <div class="content_news"><?php echo $result['address']; ?> [ <a href="mailto:"><?php echo $result['email']; ?></a> ]
                        <?php echo $result['content']; ?>
                        <div class="clearfix"></div>
                    </div>

            <?php
                }
            ?>
            <div class="clearfix"></div>
        </div>
    </div>

</div>
<div class="content_news_right fr">
    <div class="block_right_about">
        <div class="title"><span class="text">DETAIL ABOUT</span></div>
    </div>
    <?php require ("block_login.phtml"); ?>
    <?php require ("block_important.phtml"); ?>
    <?php require ("block_connect.phtml"); ?>
</div>