<div class="content_news_left fl">
  <div class="lostpass">
  <h3>FORGOT YOUR USERNAME?</h3><br /><br />
  
    <form  action="" method="post" enctype="multipart/form-data">
      <table align="center" cellpadding="0" cellspacing="0">
        <tbody>
          
        
          <tr>
         
            <td  colspan="2"><div><span > Please enter the e-mail address for your account. A verification token will be sent to you. Once you have received the token, you will be able to choose a new username for your account.<br>
              </span></div></td>
          </tr>
          <tr><td colspan="2"><br /></td></tr>
          <tr>
            <td> E-mail Address:</td>
            <td class="boderemail" style="color:red" ><input  title="Email"  style="width:200px;" maxlength="250" type="text">(*)</td>
          </tr>
         
          <tr>
            <td></td>
            <td><input  value="submit" type="submit" style="padding:5px; margin:10px;"></td>
          </tr>
        <input id="action_lost_password"  value="execute" type="hidden">
          </tbody>
      </table>
    </form>
  
  </div>
</div>
<div class="content_news_right fr">
	<?php require ("block_login.phtml"); ?>
  	<?php require ("block_important.phtml"); ?>
  	<?php require ("block_connect.phtml"); ?>
</div>