<div id="breadcrumb">
    <ul>
        <li><a href="<?php echo $this->url(array ( 'action'=> 'index','controller'=> 'index', 'module'=> 'default'),null,true )?>" title="Home">Home</a></li>
        <li class="separate"></li>
        <li class="current"><a href="" title="Membership">Membership</a></li>
    </ul>
</div>
<div class="content_news_left fl">
    <div id="about">
        <div class="title_block_about"><span class="text">
            <?php
                if(isset($this->typeMembershipID) && count($this->typeMembershipID)>0){
                    echo $this->typeMembershipID[0]['name'];
                }
            ?>
        </span></div>
        
        <div class="content_block_news_detail">
            <?php
                if(isset($this->data) && count($this->data)>0){
                    $result = $this->data[0];
                    ?>
                    <div class="title_news"><?php echo $result['title']; ?></div>   
                    <div class="content_news"><?php echo $result['content']; ?></div>
            <?php
                }
            ?>
        </div>
    </div>

</div>
<div class="content_news_right fr">
    <div class="block_right_about">
        <div class="title"><span class="text">Membership</span></div>
        <div class="content_about">
            <ul>
                <?php 
                    if(isset($this->typeMembership)){  
                        foreach ($this->typeMembership as $result) {?>
                            <li><a href="<?php echo $this->url(array ( 'action'=> 'membership','controller'=> 'index', 'module'=> 'default','id'=>$result['id']) ); ?>"><?php echo $result['name']; ?></a></li>
                    <?php
                        }
                    }
                ?>
                <li><a href="<?php echo $this->url(array ( 'action'=> 'listmembership','controller'=> 'index', 'module'=> 'default' )); ?>">List membership</a></li>
            </ul>
        </div>
    </div>
    <?php require ("block_login.phtml"); ?>
    <?php require ("block_important.phtml"); ?>
    <?php require ("block_connect.phtml"); ?>
</div>