<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#older_news").pajinate({
                    items_per_page : 4,
                    item_container_id : '#content_pagging ul',
                    nav_panel_id : '.pagging ul',
                    nav_label_first:'<< Start',
                    nav_label_prev:'< Prev',
                    nav_label_next:'Next >',
                    nav_label_last:'Last >>'

                });
    });
    
</script>
<?php require_once 'common.php';?>
<div id="breadcrumb">
	<ul>
    	<li><a href="<?php echo $this->url(array ( 'action'=> 'index','controller'=> 'index', 'module'=> 'default'),null,true )?>" title="Home">Home</a></li>
        <li class="separate"></li>
        <li class="current"><a href="" title="News">News</a></li>
    </ul>
</div>
<div class="content_news_left fl">
	<div id="the_news">
    	<div class="title_block_news"><span class="text">The News</span></div>
        
        <div class="content_block_news">
            <?php
                $i=1;
                foreach ($this->newsAll as $row) {
                    if($i%2!=0){
                        if($i++==count($this->newsAll)){
                            echo "<div class=\"items_news odd last\">";
                        }else{
                            echo "<div class=\"items_news odd\">";
                        }
                    ?>
                        
                            <a href="<?php echo $this->url(array ( 'action'=> 'newsdetail','controller'=> 'index', 'module'=> 'default','id'=>$row['id']) ); ?>" class="img fl"><img width="146" height="110" src="<?php echo 'http://'.URL_CONFIG.$row['image']; ?>" alt="<?php echo $row['title'] ?>" /></a>
                            <span class="time"><?php echo date("l, d F Y", strtotime($row['date'])); ?></span>
                            <span class="title"><a href="<?php echo $this->url(array ( 'action'=> 'newsdetail','controller'=> 'index', 'module'=> 'default','id'=>$row['id']) ); ?>"><?php echo splitString($row['title'],100); ?></a></span>
                            <div class="description"><?php echo splitString($row['description'],300); ?></div>
                            <div class="readmore fr">
                                <a href="<?php echo $this->url(array ( 'action'=> 'newsdetail','controller'=> 'index', 'module'=> 'default','id'=>$row['id']) ); ?>"></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>     
                <?php
                    }else{
                        if($i++==count($this->newsAll)){
                            echo "<div class=\"items_news even last\">";
                        }else{
                            echo "<div class=\"items_news even\">";
                        }
                ?>
                            <span class="time"><?php echo date("l, d F Y", strtotime($row['date'])); ?></span>
                            <span class="title"><a href="<?php echo $this->url(array ( 'action'=> 'newsdetail','controller'=> 'index', 'module'=> 'default','id'=>$row['id']) ); ?>"><?php echo splitString($row['title'],100); ?></a></span>
                            <div class="description"><?php echo splitString($row['description'],300); ?></div>
                            <div class="readmore fr">
                                <a href="<?php echo $this->url(array ( 'action'=> 'newsdetail','controller'=> 'index', 'module'=> 'default','id'=>$row['id']) ); ?>"></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>  
                <?php
                    }
                }
            ?>
        </div>
        <?php 
            if(count($this->oldNews)>0){
        ?>
        <div class="older_news" id="older_news">
        	<div class="title">Older news</div>
            <div class="content" id="content_pagging">
            	<ul>
                    <?php
                        foreach ($this->oldNews as $row) {
                            echo "<li><a href=\"".$this->url(array ( 'action'=> 'newsdetail','controller'=> 'index', 'module'=> 'default','id'=>$row['id']) )."\">".$row['title']."</a></li>";
                        }
                    ?>
                </ul>
            </div>
            <div class="pagging">
                <ul></ul>
            </div>
        </div>
        
        <?php }?>
    </div>

</div>
<div class="content_news_right fr">
	<div class="block_right_news">
    	<div class="title"><span class="text">News</span></div>
    </div>
	<?php require("block_login.phtml"); ?>
    <?php require("block_important.phtml"); ?>
    <?php require("block_connect.phtml"); ?>
</div>
