<div id="alertMessage" class="error"></div>
<div id="successLogin"></div>
<div class="text_success">
  
  <span>Please wait</span>
</div>

<div id="login" >
  <div class="abc"></div>
  <div class="ribbon"></div>
  <div class="inner">
    <div  class="logo" >
      </div>
    <div class="userbox"></div>
    <div class="formLogin">
      <form name="formLogin"  id="formLogin" action="" method="post" enctype="multipart/form-data">
        <div class="tip">
          <input name="username" type="text"  id="username_id"  title="Username"   />
        </div>
        <div class="tip">
          <input name="password" type="password" id="password"   title="Password"  />
        </div>
        <div style="padding:20px 0px 0px 0px ;">
          
          <div style="float:right;padding:2px 0px ;">
            <div>
              <ul class="uibutton-group">
                <li>
                  <input type="submit" class="uibutton normal" id="but_login" value="Login" />
                </li>
                <li>
                  <a class="uibutton  normal" href="#" id="forgetpass">forpassword</a>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
  <div class="clear"></div>
  <div class="shadow"></div>
</div>

<!--Login div-->
<div class="clear"></div>
<div id="versionBar" >
  <div class="copyright" >
    Design by lamweb365.com
    <span class="tip">
      <a  href="http://lamweb365.com" title="Lamweb365.com" >Lamweb365.com</a>
    </span>
    &copy; Copyright 2012  All Rights Reserved
    <span class="tip">
      <a  href="http://aati.asia" title="AATI company" >AATI company</a>
    </span>
  </div>
  <!-- // copyright-->
</div>